# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 556b6d09490e22c89e6785a14f806cb2212c63bebc3c6f5b2697803260edd1f4b4fb6c2cdd6763f1d0442fc6a58dbb17b5ec2891ba0f524af70db1dc453a8c71

test:
  secret_key_base: 2d9222f9d78408bb57b76f227369325334c0dcf8dc73b312629a03901b5728fe894cdb816e944f74754689cf5313486122c3ab688a9afd7afdf993cc52fda852

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
